### ISSUE TITLE
Block Out Dates on DayRangeSelection

### ISSUE THREAD

**Issue by BFMarks** [airbnb/HorizonCalendar#100]
Thanks for the super swifty code.  Can you walk through an example on how to safely block out dates so they are not able to be selected for DayRange Selection?

**Comment by bryankeller** [comment]
Hey @BFMarks - by blocking out, do you mean disabling selection?

You can simply ignore the selection callback for certain days, like this (I did this in the example app's `SingleDaySelectionDemoViewController`):

```swift
override func viewDidLoad() {
    super.viewDidLoad()

    title = "Single Day Selection"

    calendarView.daySelectionHandler = { [weak self] day in
      guard let self = self else { return }

      guard
        let date = self.calendar.date(from: day.components),
        !self.calendar.isDateInToday(date)
      else { return }

      self.selectedDay = day
      self.calendarView.setContent(self.makeContent())
    }
  }
```

Which will result in this behavior

https://user-images.githubusercontent.com/746571/107442803-828c7000-6aec-11eb-8d87-aa3d736f2822.mov
