### ISSUE TITLE
Programmatically set dates selection

### ISSUE THREAD

**Issue by bluelagon** [airbnb/HorizonCalendar#103]
Hi, first of all, thank you for this great library.

Here is my question, I'm wondering how to programmatically set a selection on the calendar. I have a range of dates that I would like to convert to a DayRange. The initializers of DayRange, Day and Month are all internals and so not accessible outside of the library. Is there a reason for this ? If so how should I do ? 

Thank you in advance, and again nice job.

**Comment by iosdevmax** [comment]
You can find the answer in here https://github.com/airbnb/HorizonCalendar/issues/13

**Comment by bluelagon** [comment]
Thank you @iosdevmax
