### ISSUE TITLE
DayOfWeek and MonthHeader position

### ISSUE THREAD

**Issue by nivbp7** [airbnb/HorizonCalendar#105]
Is there a way to switch between the physical locations of the DayOfWeek and MonthHeader?

**Comment by bryankeller** [comment]
Hi @nivbp7 - you cannot swap the positions for every month. You can, however, pin the days-of-the-week header to the top of the calendar, like this:

https://user-images.githubusercontent.com/746571/110220056-0598b000-7e78-11eb-9023-99a40cf0b255.mov
