### ISSUE TITLE
Day <> Date conversions

### ISSUE THREAD

**Issue by jdelaune** [airbnb/HorizonCalendar#107]
Is there an undocumented way of converting swift Dates to the `Day` struct and vice versa?

I tried writing an extension myself but I cannot initialise the `Month` struct because of the internal property `isInGregorianCalendar`. I think the `init()` would need to be explicitly marked as `public` for me to use it.

Thanks

**Comment by bryankeller** [comment]
Hey @jdelaune, you can think of `Day` and `Month` as wrappers for `DateComponents` that have better type safety. The public API of `HorizonCalendar` will pass these to you, and you should convert them back to `Date` instances.

You'll also notice that all of `HorizonCalendar`'s public API takes `Date` instances, so there's no reason for your feature code to be initializing these manually.

If you want to convert `Day` to `Date`, do `let date = calendar.date(from: day.components)`
