### ISSUE TITLE
Month label showing YEAR MXX after upgrading from version 1.5.0

### ISSUE THREAD

**Issue by rs658726** [airbnb/HorizonCalendar#108]
Hello,

After upgrading from version 1.5.0 to 1.8.0, I noticed that the month label was showing as YEAR MXX (for example: 2021 M03 instead of March 2021) -- Any idea why this is happening? Note that I'm not using any custom view for the month headers.

Thanks!

**Comment by bryankeller** [comment]
@rs658726 thanks for the bug report! What Calendar / locale are you using? When you initialize `CalendarViewContent`, you need to pass in an instance of `Calendar` - what does this look like for you? If you're omitting the `calendar` argument when initializing `CalendarViewContent`, then it should be using `Calendar.current` by default. What locale is this for you?

For context, for en-US locale, the default month headers look correct in the example app.

**Comment by bryankeller** [comment]
@rs658726 could I get some more details when you have a chance? Thanks!

**Comment by rs658726** [comment]
Sorry for the delay @bryankeller 

I'm using the default locale and this is how I initialize calendar view content:

`CalendarViewContent(calendar: Calendar(identifier: :gregorian), visibleDateRange: startDate ... endDate, monthsLayout: monthsLayout)`

**Comment by bryankeller** [comment]
Thanks @rs658726 , the problem is you're creating a brand new calendar instance that doesn't have a `Locale` set. If you don't want to use `Calendar.current`, you can do this to solve your problem:

```swift
var calendar = Calendar(identifier: .gregorian)
calendar.locale = Locale(identifier: "en_us") // you can read Calendar.current.locale instead to ensure that this translates properly

let content = CalendarViewContent(
    calendar: calendar,
    visibleDateRange: startDate...endDate,
    monthsLayout: monthsLayout)
```
