### ISSUE TITLE
Thread 1: Assertion failed:   Calendar metrics and size resulted in a negative-or-zero amount of remaining height

### ISSUE THREAD

**Issue by felipeflorencio** [airbnb/HorizonCalendar#109]
I have tried everything, at the moment I have just copy and past the code from the example and still doesn't work.

I want to show a calendar, horizontal style, but the app always crash on the validateCalendarMetrics method.

More specifically on this assert:

```
 assert(
        availableHeight > 0,
        """
          Calendar metrics and size resulted in a negative-or-zero amount of remaining height
          (\(availableHeight) points) after allocating room for calendar elements. If ignored, this
          will cause very odd / incorrect layouts.
        """)```
        
        
       My code is just the one from the example but with just one view controller that I present modally.
       
       Is the range selection.
       
       
       Anyone has any idea how to fix this?

**Comment by felipeflorencio** [comment]
I found out that the problem is that the container that I was adding this CalendarView was smaller than the content size of the calendar.

This error could be better explained, so I will leave this comment so others can understand it.

If you get this error means that where you are adding it needs to be bigger.

A suggestion is the container view that you add your calendar view beside set size set content hugging priority

**Comment by tanchik95** [comment]
thanks, this helped me
I added width and height to the constructs
