### ISSUE TITLE
How to high light particular array of dates?

### ISSUE THREAD

**Issue by ssowri1** [airbnb/HorizonCalendar#112]
I want to highlight the dates which I am having events. Could you please help me to have the solution?

**Comment by bryankeller** [comment]
Do you want to highlight day ranges? Or provide custom styling for individual days? If you look at the code in the Example project, I think you will see something similar to your goal design.

You should also read this documentation:
- https://github.com/airbnb/HorizonCalendar#providing-a-custom-view-for-each-day
- https://github.com/airbnb/HorizonCalendar#adding-a-day-range-indicator

**Comment by nazartino** [comment]
> I want to highlight the dates which I am having events. Could you please help me to have the solution?

Hello, do you have a solution yet?

**Comment by bryankeller** [comment]
@nazartino have you looked at the documentation that I linked above? I also think the Example Project should help you understand how to do this.

If you want to change the appearance of certain days, then you'll need to do something like this in your feature code:

```swift
.withDayItemModelProvider { day in
  let date = calendar.date(from: day.components)!
  if isEventOnDate(date) {
    // Return a `CalendarItemModel` representing the view for your "event" day
  } else {
    // Return a `CalendarItemModel` representing the view for your "non-event" day
  }
}
```
