### ISSUE TITLE
Localization of the dates 

### ISSUE THREAD

**Issue by rizwan95** [airbnb/HorizonCalendar#120]
Hi! Is it possible to localize the dates inside the calendar?

**Comment by bryankeller** [comment]
Hi @rizwan95 - yes. You'll need to make sure that you pass in the correct `Calendar` instance when initializing `CalendarView`. To use the device's current locale, you can use `Calendar.current`.

In your `DayView`, you will then need to use a DateFormatter with the correct locale and date format set. Then, set your day view's label text to the localized date string.

In general, I would recommend reading up on `Calendar` and `DateFormatter`. There are many resources, but here is one that I found just now https://learnappmaking.com/swift-date-datecomponents-dateformatter-how-to/.

**Comment by rizwan95** [comment]
Thank you so much!
