### ISSUE TITLE
iPad is not supported

### ISSUE THREAD

**Issue by isaacthedeveloper** [airbnb/HorizonCalendar#125]
When I try to run this on the iPad I get the following error. is Ipad supported? 
ERROR:
Thread 1: Assertion failed:   Calendar metrics and size resulted in a negative-or-zero amount of remaining height
  (-460.5 points) after allocating room for calendar elements. If ignored, this
  will cause very odd / incorrect layouts
Assert Code:
```
assert(availableHeight > 0,
        """
          Calendar metrics and size resulted in a negative-or-zero amount of remaining height
          (\(availableHeight) points) after allocating room for calendar elements. If ignored, this
          will cause very odd / incorrect layouts.
        """)
    }
```

**Comment by isaacthedeveloper** [comment]
@bryankeller

**Comment by bryankeller** [comment]
@isaacthedeveloper a temporary workaround would be to increase the available height of `CalendarView`. I agree that this behavior is super fragile and makes working with horizontal calendars really difficult. I think that the ideal behavior would be to have the calendar's height be determined based on the width + metrics that you set. I'll look into making this improvement soon.

**Comment by bryankeller** [comment]
Starting in version 1.11.0 (just released), `CalendarView` now has an `intrinsicContentSize.height` equal to the exact amount of space needed to display 1 month, given the current width / other layout metrics. That means that you can add a horizontally-scrolling `CalendarView` to your view hierarchy, constrain its width, and the height will be set based on the `intrinsicContentSize`.
