### ISSUE TITLE
Disable days of week view

### ISSUE THREAD

**Issue by Larson2240** [airbnb/HorizonCalendar#126]
Hey guys! 
I'm struggling to find a way to disable view with days of week. Wee don't want to show it with every month. Please advice

**Comment by bryankeller** [comment]
Hi @Larson2240 - are you using a horizontal or vertical calendar? If you're using a vertical calendar, then you can use a `monthsLayout` like this to show the days of the week only at the top (pinned) instead of repeated in every month. There is no option to do this for horizontal calendars yet.

```swift
CalendarViewContent(
  visibleDateRange: ...,
  monthsLayout: .vertical(options: VerticalMonthsLayoutOptions(pinDaysOfWeekToTop: true))
```

**Comment by kirankhalkar** [comment]
@protosse - Did you resolved this issue?  If yes could you please share the step..

**Comment by euthimis87** [comment]
I had the same issue, so I had to configure my own day-of-week view and give it a negative top padding.
Here is my solution to fix this margin issue:

```swift
.dayOfWeekItemProvider { _, weekdayIndex in
    Rectangle()
        .background(.white)
        .foregroundStyle(.clear)
        .overlay {
            Text(Calendar.current.veryShortWeekdaySymbols[weekdayIndex])
        }
        .padding(.top, -8)
    .calendarItemModel
}
```
