### ISSUE TITLE
Question: How can I set by default a selected Day ?

### ISSUE THREAD

**Issue by gwennguihal** [airbnb/HorizonCalendar#13]
Hi,

First, thanks for you work, it's amazing!
The API to tranform a Date into Day is private, so how can I select a Day by default ?
Thanks.

**Comment by bryankeller** [comment]
Hey @gwennguihal ! Good question. First I just want to clarify that `HorizonCalendar` has no concept of selected vs. unselected days. You can think about `HorizonCalendar` as being a presentation-only component. All selected vs. unselected business logic should live in your feature code.

`HorizonCalendar` does provide a closure property that is called whenever a day is tapped / selected. Once the closure is called, `HorizonCalendar` does not store any state internally about that selection / tap event.

If you want to indicate selection, you should implement the `dayItemProvider` closure on `CalendarViewContent` That closure is invoked with a `Day` parameter for each visible day in the calendar. When you encounter a `Day` that you'd like to show as selected, you can return a `CalendarItem` that represents a selected day view.

Here an example implementation that will make the background color of today a different color:

```swift
let calendar = Calendar.current // use whatever calendar you want here. `current` will use the system's calendar.

let calendarViewContent =  CalendarViewContent(calendar: calendar, ...)
  .withDayItemProvider { day in
      let date = calendar.date(from: day.components) // Convert the Day to a Date so we can use it with Calendar

      if calendar.isDateInToday(date) {
        return CalendarItem<SelectedDayView, Day>(
          viewModel: day,
          styleID: "Default",
          buildView: { SelectedDayView(color: .blue) },
          updateViewModel: { dayView, day in
            dayView.text = "\(day.day)"
          })
      } else {
        return CalendarItem<NormalDayView, Day>(
          viewModel: day,
          styleID: "Default",
          buildView: { NormalDayView() },
          updateViewModel: { dayView, day in
            dayView.text = "\(day.day)"
          })
      }
  }
```

This implementation assumes you have a `UIView` subclass called `SelectedDayView` and `NormalDayView`.

---

> The API to transform a Date into Day is private, so how can I select a Day by default ?

If you need to compare `Day`s, it's usually better to convert to a `Date` via `calendar.date(from: day.components)`, although this might not always be necessary. For example, if you want to show the first day of each month as selected, you could change the above code to this, and no conversion to `Date` will be needed:

```swift
let calendar = Calendar.current // use whatever calendar you want here. `current` will use the system's calendar.

let calendarViewContent =  CalendarViewContent(calendar: calendar, ...)
  .withDayItemProvider { day in
      if day.day == 1 {
        return CalendarItem<SelectedDayView, Day>(
          viewModel: day,
          styleID: "Default",
          buildView: { SelectedDayView(color: .blue) },
          updateViewModel: { dayView, day in
            dayView.text = "\(day.day)"
          })
      } else {
        return CalendarItem<NormalDayView, Day>(
          viewModel: day,
          styleID: "Default",
          buildView: { NormalDayView() },
          updateViewModel: { dayView, day in
            dayView.text = "\(day.day)"
          })
      }
  }
```

**Comment by gwennguihal** [comment]
Thanks you for the answer. It helped me ;)

**Comment by nomi1315** [comment]
Hi @gwennguihal , have you achieve this implementation?
