### ISSUE TITLE
Disable days before minimum  date

### ISSUE THREAD

**Issue by ghadeermohameedelmahdy** [airbnb/HorizonCalendar#133]
howa can we disable those days as they cannot be selected anymore.
<img width="324" alt="Screen Shot 2021-07-25 at 11 00 12 PM" src="https://user-images.githubusercontent.com/29740609/126913373-cbc23c2f-f5eb-4fb8-a845-b6562e7532bb.png">

**Comment by bryankeller** [comment]
@ghadeermohameedelmahdy you can ignore taps for certain items in your `daySelectionHandler`

calendarView.daySelectionHandler = { [weak self] day in
  if isDaySelectable(day) { 
    self?.selectedDay = day
  }
}
