### ISSUE TITLE
didEndDecelerating callback method is not getting called for the first month

### ISSUE THREAD

**Issue by rizwan95** [airbnb/HorizonCalendar#135]
When we swipe through and come back to the first month, didEndDecelerating method is not being called if it is the first month.

**Comment by bryankeller** [comment]
@rizwan95 I can confirm that I'm seeing this behavior if the calendar has no declaration animation after you lift your finger. This is the same behavior as `UIScrollView`'s `didEndDecelerating`. 

You will need to also implement `calendarView.didEndDragging`... I'm now realizing that I should have included a boolean on that closure callback to indicate whether the calendar _will_ decelerate or not.

I've implemented a fix here. Once you update to `v1.9.0`, you can use `calendarView._didEndDragging = { visibleDayRange, willDecelerate in ... }`

**Comment by rizwan95** [comment]
Awesome! Your proposed fix should solves the issue! Thanks a lot @bryankeller

**Comment by bryankeller** [comment]
@rizwan95 v1.9.0 has been released with the new `_didEndDragging` API, which includes a flag for whether the scroll view will decelerate or not 🙂
