### ISSUE TITLE
Issue with DayRange instantiation

### ISSUE THREAD

**Issue by bluelagon** [airbnb/HorizonCalendar#136]
Hi everyone, I'm using the HorizonCalendar version 1.8.8. 

I've met an issue with the method `withDayRangeItemModelProvider` in `CalendarViewContent`. The transformation from `dateRanges`to `dayRanges` seems to have an issue that I don't understand.
For the parameter `dateRanges` I have `2021-09-09` to `2021-09-10`:
`(lldb) po dateRanges
▿ 1 element
  ▿ 0 : ClosedRange(2021-09-09 00:00:00 +0000...2021-09-10 00:00:00 +0000)
    ▿ lowerBound : 2021-09-09 00:00:00 +0000
      - timeIntervalSinceReferenceDate : 652838400.0
    ▿ upperBound : 2021-09-10 00:00:00 +0000
      - timeIntervalSinceReferenceDate : 652924800.0`
   
 And after the line 275 in `CalendarViewContent`:
`let dayRanges = Set(dateRanges.map { DayRange(containing: $0, in: calendar) })`

I get this set of `DayRange` which contains dates with one day before which I passed: `2021-09-08` to `2021-09-09`:
`(lldb) po dayRanges
▿ 1 element
  ▿ 0 : ClosedRange(2021-09-08...2021-09-09)
    ▿ lowerBound : 2021-09-08
      ▿ month : 2021-09
        - era : 1
        - year : 2021
        - month : 9
        - isInGregorianCalendar : true
      - day : 8
    ▿ upperBound : 2021-09-09
      ▿ month : 2021-09
        - era : 1
        - year : 2021
        - month : 9
        - isInGregorianCalendar : true
      - day : 9`
  
Could someone tell me more about it ?
For information I've change my timezone to PST for having that behavior.

**Comment by bryankeller** [comment]
@bluelagon were you able to resolve your issue? This sounds like an issue with your date creation code. Make sure the `NSCalendar` instance you're working with has the correct timezone set. The example project does things correctly, so refer to that if something still doesn't seem right! Good luck 🙂

**Comment by bluelagon** [comment]
Hi @bryankeller thank you for your reply. Indeed it was an issue with the timezone I set.
