### ISSUE TITLE
How to set the size of day items?

### ISSUE THREAD

**Issue by Mordil** [airbnb/HorizonCalendar#139]
I'm having a hard time understanding how to set the size of items to get a more compact month.

When the horizontal/vertical day margins are `0`, they end up being huge - like 80pt squares. When I set the margins to be `32`, then they're appropriately sized, but they're still taking up the same space (because of the margins)

How do I configure the calendar so that the items are smaller, like `32` with `0` margins?

**Comment by bryankeller** [comment]
Hi @Mordil , day items grow to take up the available width. If you're using a vertical months layout, you'll want to set some layout margins on your calendar like this:

```swift
calendarView.layoutMargins.leading = 50
calendarView.layoutMargins.trailing = 50
```

This will decrease the amount of horizontal space, making each day smaller, while also insetting the content from the edges by `50` on each side.

**Comment by Mordil** [comment]
@bryankeller What if it's a horizontal calendar and I want to only display a single month?

**Comment by bryankeller** [comment]
@Mordil for your horizontal scenario, you can decrease the width of the calendar to make items smaller

**Comment by bryankeller** [comment]
From the example project...

Before
===
```swift
NSLayoutConstraint.activate([
        calendarView.centerYAnchor.constraint(equalTo: view.layoutMarginsGuide.centerYAnchor),
        calendarView.heightAnchor.constraint(equalToConstant: 400),
        calendarView.leadingAnchor.constraint(
          greaterThanOrEqualTo: view.leadingAnchor),
        calendarView.trailingAnchor.constraint(
          lessThanOrEqualTo: view.trailingAnchor),
        calendarView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
        calendarView.widthAnchor.constraint(lessThanOrEqualToConstant: 375)
      ])
```

![Simulator Screen Shot - iPhone 8 - 2021-09-12 at 17 59 14](https://user-images.githubusercontent.com/746571/133009639-0a14fc9a-d56f-4693-8254-98e0c7bcdb63.png)

-----

After
===

```swift
NSLayoutConstraint.activate([
        calendarView.centerYAnchor.constraint(equalTo: view.layoutMarginsGuide.centerYAnchor),
        calendarView.heightAnchor.constraint(equalToConstant: 400),
        calendarView.leadingAnchor.constraint(
          greaterThanOrEqualTo: view.leadingAnchor),
        calendarView.trailingAnchor.constraint(
          lessThanOrEqualTo: view.trailingAnchor),
        calendarView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
        calendarView.widthAnchor.constraint(lessThanOrEqualToConstant: 300) // <-------------------
      ])
```

![Simulator Screen Shot - iPhone 8 - 2021-09-12 at 18 00 34](https://user-images.githubusercontent.com/746571/133009687-08e1284e-346c-477f-b052-31b120e9ffa3.png)

**Comment by bryankeller** [comment]
FYI, I also added a new API to change the aspect ratio of each day https://github.com/airbnb/HorizonCalendar/blob/master/Sources/Public/CalendarViewContent.swift#L119-L128

I think you should have all of the tools needed to make your days appear at the correct size for your designs.
