### ISSUE TITLE
Storyboard Support

### ISSUE THREAD

**Issue by justdan0227** [airbnb/HorizonCalendar#145]
I may be missing it but is there storyboard support in the demo?

**Comment by bryankeller** [comment]
@justdan0227 that's correct - no storyboard support in the demo. You're welcome to add it if you'd like! No idea how well IBDesignable and IBInspectable work these days but you're welcome to add support for it if you'd like 🙂

If you do decide to tackle this, my only ask would be that we treat it as its own standalone demo, and keep the remaining examples in code as-is.

**Comment by bryankeller** [comment]
And just to be clear, this isn't something I'll be prioritizing work on. But a PR with a proper demo is welcome! Closing as "Won't fix."
