### ISSUE TITLE
Disable an range of dates

### ISSUE THREAD

**Issue by Max8868** [airbnb/HorizonCalendar#149]
Hello everyone, everything good?

I have a slight doubt, I want to insert a range of disabled dates in the calendar, but reading and rereading the structure I still haven't been able to find a way to insert an array of dates and make them "obfuscated", for example, if I'm using this framework for an agenda, I'd like to limit a few days and leave them "disabled", I didn't want to open this issue because I thought it would be easier to find a way to do this but I couldn't find it, I saw that there are two others issues [How to disable future date in calendar?](https://github.com/airbnb/HorizonCalendar/issues/64) and [Block Out Dates on DayRangeSelection](https://github.com/airbnb/HorizonCalendar/issues/100) with doubts similar to mine but although similar, but the solution given to one of the cases doesn't help me much because it doesn't allow me to enter more than one date.

I don't even know if it's possible to do this in the current state of the lib, if it's something too fancy please let me know so I can think of how to adapt this for it, I'm asking for help because I actually couldn't think of any solution with the code existing.

I thank and congratulate you for the development of this lib

**Comment by bryankeller** [comment]
Hey @Max8868 , happy to help! When you say "disabled range of dates," what is it exactly that you want? Do you want:

1. To prevent certain days from being tapped / interacted with?
2. To change the appearance of certain days so that they look disabled (crossed out? faded / greyed out? something else?)

Check out the Airbnb app - we use HorizonCalendar for all of our calendars. If you view a listing and select dates, you'll see that we prevent certain ranges of dates from being selected based on a host's availability. 

![image](https://user-images.githubusercontent.com/746571/140001888-09a44d96-417a-43a9-812e-bd676a85d4f2.png)

Let me know how I can help!

**Comment by Max8868** [comment]
Hello @bryankeller 
would be basically that, my point is that I couldn't implement it here on my side 😅

**Comment by bryankeller** [comment]
@Max8868 you need to implement something like this:


```swift

private func viewDidLoad() {
  calendarView.daySelectionHandler = { [unowned self] day in
    guard !self.isDayDisabled(day) else { return }
    self.selectedDay = day
  }
}

private func makeContent() -> CalendarViewContent {
  return CalendarViewContent(...)
    ...
    .withDayItemModelProvider { [unowned self] day in
      if day == self.selectedDay {
        return CalendarItemModel<SelectedStyleDayView>(...)
      } else if self.isDayDisabled(day) {
        return CalendarItemModel<DisabledStyleDayView>(...)
      } else {
        return CalendarItemModel<NormalStyleDayView>(...)
      }
    }
}

private func isDayDisabled(_ day: Day) -> Bool {
  let date = calendar.date(from: day) // convert Day to Date
  // determine if date should be disabled or enabled, and return either true or false
}

```

You can create separate UIView subclasses for `SelectedStyleDayView`, `DisabledStyleDayView`, and `NormalStyleDayView`. Or, you can create one `DayView` type (or use the build in `DayView` type) and adjust its appearance using `InvariantViewProperties`. Either approach works.

Hope this helps!

**Comment by Max8868** [comment]
wow, thank you very much, I was trying to do this for some time
