### ISSUE TITLE
Question: How to display current day and Month View 

### ISSUE THREAD

**Issue by iyinraphael** [airbnb/HorizonCalendar#15]
Hello,

First, I really appreciate how simple it is to implement this framework.

How do I implement the calendar view to display the current month and day as default?

**Comment by bryankeller** [comment]
Hi @iyinraphael , glad you’re enjoying using it!

`CalendarViewContent`’s `visibleDateRange` controls the visible range of dates to display. To create `Date` instances for pass in, use Calendar APIs. 

For example, if you want to display a calendar view that shows the current month -> three months in advance:

```swift
let today = Date()
let threeMonthsFromToday = Calendar.current.date(byAdding: DateComponents(month: 3), to: today)

let content = CalendarViewContent(calendar: Calendar.current, visibleDateRange: today...threeMonthsFromToday, monthsLayout: .vertical(...))
``` 

—-

If you’re new to working with Apple’s Calendar / Date types, check this out http://swiftdeveloperblog.com/code-examples/add-days-months-or-years-to-current-date-in-swift/

—-

Good luck 🙂

**Comment by iyinraphael** [comment]
Thank you.

**Comment by ljhao24** [comment]
What if I want to  display current day and also let users to swipe to view the previous month?
