### ISSUE TITLE
Wrong dates in New Year

### ISSUE THREAD

**Issue by kekanol** [airbnb/HorizonCalendar#151]
```swift
private func makeContent() -> CalendarViewContent {
        let startDate = Date().startOfMonth()
        let endDate = calendar.maxDate
        
        let monthHeaderDateFormatter = DateFormatter()
        monthHeaderDateFormatter.calendar = calendar
        monthHeaderDateFormatter.locale = calendar.locale
        monthHeaderDateFormatter.dateFormat = DateFormatter.dateFormat(
            fromTemplate: "MMMM YYYY",
            options: 0,
            locale: calendar.locale ?? Locale.current)
        
        return CalendarViewContent(
            calendar: calendar,
            visibleDateRange: startDate...endDate,
            monthsLayout: monthsLayout)
            .withInterMonthSpacing(24)
            .withVerticalDayMargin(8)
            .withHorizontalDayMargin(8)
            .withCustomMonthHeaderItemModelProvider(calendar, monthHeaderDateFormatter)
            .withCustomDayOfWeekItemModelProvider(monthHeaderDateFormatter)
            .withCustomDayItemModelProvider(presentationModel.availableDays, selectedDate)
    }
```

I have func like this, and my locale is Russian. Calendar shows each first month in year with past year. For example i have december 2021, and then january 2021, and then february 2022

if i set locale to Locale(identifier: "en"), this problem goes away, but all names are in english

**Comment by bryankeller** [comment]
This sounds very strange - can you post a screenshot of the bug + intended behavior? Where is your `Calendar` instance coming from? Are you using `Calendar.current`?

**Comment by bryankeller** [comment]
Another question to help narrow this down to a HorizonCalendar bug or a feature-code bug: does the example app included in the repository behave correctly? If so, then it seems like it might be a bug in your feature code.

**Comment by bryankeller** [comment]
In the Example app, I tried doing this:

```swift
override func makeContent() -> CalendarViewContent {
    let calendar = Calendar.current
    let startDate = calendar.date(from: DateComponents(year: 2021, month: 12, day: 01))!
    let endDate = calendar.date(from: DateComponents(year: 2022, month: 03, day: 31))!
    return CalendarViewContent(
      calendar: calendar,
      visibleDateRange: startDate...endDate,
      monthsLayout: .vertical(options: .init(pinDaysOfWeekToTop: false, alwaysShowCompleteBoundaryMonths: true)))
}
```

In Settings, I set the region to Russia and the language to Russian. I also added Russian localization to the Example app.

| en_RU | ru_RU |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/746571/147023658-85f4e5fe-be6d-4750-8cba-5c4c657d3280.png) | ![image](https://user-images.githubusercontent.com/746571/147023532-27029682-5936-4428-9a4f-cc7791011af6.png) |

**Comment by bryankeller** [comment]
@kekanol I think I figured out your bug. It's related to this thread: https://twitter.com/vishalmalvi_/status/1475835430067052546?s=21
