### ISSUE TITLE
.horizontal(monthWidth:) deprecated

### ISSUE THREAD

**Issue by blg-nb** [airbnb/HorizonCalendar#154]
Hello,

i have problem with init from CalendarViewContent

`CalendarViewContent(calendar: calendar,
                                   visibleDateRange: startDate...endDate,
                                   monthsLayout: .horizontal(monthWidth: monthWidth))`

The .horizontal(monthWidth:) is now deprecated and I don't understand  the new .horizontal(options:).

Can someone help me?

**Comment by bryankeller** [comment]
Hi @blg-nb ,

The new API makes you specify how many months you want to be visible (default of 1). The width of each month is determined based on the frame of your `CalendarView` instance, and the number of months you want to be viable. For example, if you have a `CalendarView` that's 300pt wide, and you specify 2 visible months, then each months will be ~150pt wide.

Take a look at the horizontal example in the included example project. Hopefully that makes it clear how to use it!

**Comment by blg-nb** [comment]
thanks, now it works
