### ISSUE TITLE
Making calendar smaller while maintaining maximum of 1 visible month.

### ISSUE THREAD

**Issue by tareksabry1337** [airbnb/HorizonCalendar#163]
First of all hats off for this amazing library I have been using it all over my projects and it's making my life way easier than I expected.

I have a use case to implement a calendar that looks like this.

<img width="533" alt="Screen Shot 2022-02-18 at 10 03 24 AM" src="https://user-images.githubusercontent.com/45688300/154642519-978fa335-eb2d-4228-a6cd-b0103e2ed5ff.png">
 
The only problem though that I can't achieve this kind of "smaller" size unless I provide more than one 1 visible month.

Is there anything possible to do to achieve such layout ?

Thanks a bunch !

**Comment by bryankeller** [comment]
Thanks for the kind words! Glad the library has been useful for you 🙂 

Can you clarify what you mean by "smaller"? Is this a vertically-scrolling or horizontally-scrolling calendar? I do see 2 things in this design that will be difficult to do without some enhancements to the library:

- the month has an inset background color (not easily possible today)
- the 1st day of the next month appears on the same row of the current month (not at all possible today)

Which aspect were you referring to in your question?

**Comment by bryankeller** [comment]
Ah I understand, thanks for clarifying.

HorizonCalendar determines the height of the calendar based on the width and the size of your days, number of visible months, vertical inter-day spacing, etc. For example, by increasing the width of the calendar, it's height will increase too.

If you want the height to be exactly 250pt, you'll need to first pick a width for your calendar. Once you have a constant width value (e.g. 300pt), then you can start adjusting other calendar metrics like the day aspect ratio, vertical spacing, and top / bottom layout margins to try to get the height to be 250pt tall. It will take some trial and error but you should be able to figure it out with some tries :)

**Comment by tareksabry1337** [comment]
Ah, that's actually a good idea, thanks for the help !
