### ISSUE TITLE
Incompatible with prefersLargeTitles

### ISSUE THREAD

**Issue by davidrothera** [airbnb/HorizonCalendar#18]
When added as the first subview (or only subview) to a view within a navigation controller that has the `prefersLargeTitles` property set to `true` there is an issue where the large title will show the large title but if you scroll down and back to the top the large title never comes back which is the usual behaviour.

This is reproducible using the demo app by adding the below to the `viewDidLoad` of the DemoPickerViewController:

```swift
navigationController?.navigationBar.prefersLargeTitles = true
```

**Comment by bryankeller** [comment]
@davidrothera this is fixed in `v1.1.3`. Thanks again for the report 🙂
