### ISSUE TITLE
Is it possible to disable days?

### ISSUE THREAD

**Issue by matthiasvanwoensel** [airbnb/HorizonCalendar#186]
Hi, i'm working on a restaurant app and I need to disable some days at the calendar (because of closing days of the restaurant etc). I know this is possible at Airbnb, but I can't find an example of this at the docs.. Can someone help me please? :)

something like this: 

https://github.com/airbnb/HorizonCalendar/blob/master/Docs/Images/experience_reservation.png

Matthias

**Comment by bryankeller** [comment]
Hey @matthiasvanwoensel - can you just ignore those selections in your `daySelectionHandler`? If you want the day to visually look disabled, you can return a grayed-out version of your view / `CalendarItemModel` from `dayItemProvider`. Does that make sense?

**Comment by bryankeller** [comment]
Great! Happy to hear :)

**Comment by alexisgarciaa** [comment]
i would love to hear if this option to make a day unavailable, can be done using swiftui
