### ISSUE TITLE
 How can I add bottom contentInsets scroll view?

### ISSUE THREAD

**Issue by misha8414** [airbnb/HorizonCalendar#19]
Hello, is it possible to add bottom contentInsets for scroll view?

**Comment by bryankeller** [comment]
Hi @misha8414 - I'm working on supporting this soon. Until then, a temporary workaround might be to constrain your calendar to the layout margins so that the content isn't overlapped.

**Comment by JulienLevallois** [comment]
I have the same problem. I need top & bottom contentInsets for the scrollview

**Comment by alex-sarkisov** [comment]
For now I added top inset, setting the month bottom inset to 0
> .withMonthDayInsets(UIEdgeInsets(top: 20, left: 20, bottom: 0, right: 20))
and adding top padding to the custom month view title
> titleLabel.topAnchor.constraint(equalTo: topAnchor, constant: 20)

**Comment by bryankeller** [comment]
@misha8414 @JulienLevallois @alex-sarkisov I've added the ability to set insets using `UIView`'s `layoutMargins` and `directionalLayoutMargins` properties. The changes are included in `v1.2.0`. Thank you again for reporting this and for your patience as I investigated a good way to do this 🙂
