### ISSUE TITLE
How we can Date convert Day?

### ISSUE THREAD

**Issue by newboys** [airbnb/HorizonCalendar#190]
Hello,
Thanks for making this library and open source.

How can I convert Date  to Day?

**Comment by tommyming** [comment]
What do you mean by convert Date to Day? Would you please provide more details?

**Comment by bryankeller** [comment]
There is never a reason to convert a `Date` to a `Day` - all of HorizonCalendar's public APIs take `Date`s as inputs. In your feature code, only work with `Date` instances.

Please refer to the example project to see how to properly use the library from feature code.
