### ISSUE TITLE
Any official tag soon?

### ISSUE THREAD

**Issue by Andrewangeta** [airbnb/HorizonCalendar#194]
Are there any plans to tag a new release or are we relegated to stick with a specific branch?
Wanted to use the SwiftUI flavor for `.calendarItemModel` which was in the README but realized it wasn't tagged at all.

**Comment by bryankeller** [comment]
I'll tag it tomorrow - sorry for the wait :)

**Comment by bryankeller** [comment]
v1.15.0 is available!

**Comment by adeds** [comment]
waiting for v1.17.0 🚀
