### ISSUE TITLE
Scroll(toMonth or toDay ...) not available in SwiftUI? [Question]

### ISSUE THREAD

**Issue by piter1995** [airbnb/HorizonCalendar#219]
Hi guys, I successfully implemented using the `CalendarViewRepresentable` the calendar in my SwiftUI project. However I can't figure out a way to scroll to current day or month. Apparently the `CalendarViewRepresentable` does not have any public method. Any suggestions? Thanks!

**Comment by bryankeller** [comment]
Fixed on master! https://github.com/airbnb/HorizonCalendar/pull/237
