### ISSUE TITLE
Days of week pinned view frame not enough to hide content that passes behind

### ISSUE THREAD

**Issue by ecunha-ta** [airbnb/HorizonCalendar#225]
When I scroll the calendar I can see the days passing behind the top `days of week` bar. This happens both on the sides and on top. I have read the documentation but I cant find a way to set the frame of the bar week days to fill the entire width for example..

In my example below it's possible to see the circles passing on the `days of week` bar since the background frame is not big enough.. I mean the width of the bar is too small for the content of the days.. anyway we can allow the bar to fill the width of the screen? Otherwise we can see the content on the sides while scrolling..

Thanks for the lib :D 

![image](https://user-images.githubusercontent.com/77671235/231752189-ece0b310-7cec-45a8-a6a8-2a8fcc18c4e7.png)

**Comment by Nam-Namazov** [comment]
Hello, I have this issue too, for me work to write 'layoutMargins.top = 0' of your calendarView when you declare it. I hope this will help you.

**Comment by ecunha-ta** [comment]
@bryankeller any news on this? Are you guys planing to add this? IS there a way I am missing to do this? 
Just to wonder if I should do a fork.. 

Thanks for the help

**Comment by ecunha-ta** [comment]
Are there any updates on this?

**Comment by bryankeller** [comment]
@ecunha-ta about to merge a fix! Sorry for the delay. https://github.com/airbnb/HorizonCalendar/pull/239

**Comment by ecunha-ta** [comment]
Thanks a lot! 🙏

**Comment by ecunha-ta** [comment]
In this new MR of yours it is possible to achieve this via SwiftUI? :

https://github.com/airbnb/HorizonCalendar/blob/master/Docs/Images/stay_availability.png < 
Or even personalize the header background not just that line below.. 

Thanks once more for looking at this.

**Comment by bryankeller** [comment]
@ecunha-ta the screenshot you posted of the Airbnb app is actually 2 views - there's a custom header view at the top of the view controller, and a CalendarView _below it_. HorizonCalendar starts rendering at the pinned days-of-the-week row. Right now, there's limited customization available for that row. You can provide a different view for each day of the week, and specify the divider visibility, but that's it.

Can you show me the design you're trying to achieve? Maybe it'll give me some inspiration for an improved API :)
