### ISSUE TITLE
Change year

### ISSUE THREAD

**Issue by r0otx** [airbnb/HorizonCalendar#229]
Hello! How I can change year and re-render calendar? I have selector which increment or decrement year and I want change current calendar. Thank you!

**Comment by alexisgarciaa** [comment]
Hii!! can you share how you update a Day type ? are you using swiftUI?

**Comment by r0otx** [comment]
> Hii!! can you share how you update a Day type ? are you using swiftUI?

I"m use UIKit, I did"t make this logic, have label which contain year and two chevrons, left or right. If click left action decrement current year, but I can"t update calendar. 😐

**Comment by bryankeller** [comment]
@r0otx you should call scrollToMonth (public function on CalendarView) in response to your button taps. Please reopen if this doesn't solve your issue.
