### ISSUE TITLE
Unselect the specific day in range.

### ISSUE THREAD

**Issue by yuvarajb1992** [airbnb/HorizonCalendar#232]
@brynbodayle 
How to unselect the specific day in the range selection?
For example, I have selected **(1...15)** days and then I unselect the **7,8** and I want to separate the ranges like **(1..6)** and **(9..15)**
How can I achieve that?

OR

How to change specific day background colour in the date range, Like the above example I want to change **(7,8)** days colour in the (1...15) range.

**Comment by bryankeller** [comment]
@yuvarajb1992 you need some kind of model (in your feature code) to track which days are highlighted and which aren't. Then you can check that model in your `dayItemProvider` closure to change the styling of the day view.
