### ISSUE TITLE
SwiftUI: Putting the CalendarViewRepresentable inside a ScrollView doesnt work

### ISSUE THREAD

**Issue by alex-taras** [airbnb/HorizonCalendar#247]
If i place the CalendarViewRepresentable configured as horizontal inside a vertical SwiftUI ScrollView doesnt show the CalendarViewRepresentable unless i set a hardcoded frame to it. If i just put the CalendarViewRepresentable inside a VStack, everything is fine, i dont need to provide a frame to it.

**Comment by bryankeller** [comment]
@alex-taras i believe this is fixed now. Can you pull the latest version and check?

**Comment by bryankeller** [comment]
I made more improvements to this recently. This should be fixed now in latest commit.
