### ISSUE TITLE
Fixed Day Header 

### ISSUE THREAD

**Issue by mosaic-engineering** [airbnb/HorizonCalendar#26]
Hello! Love the library so far! Have a quick question.

**Is it possible to have a fixed day header? Not sure what they are exactly called but here's a picture of it.**
<img width="274" alt="Screen Shot 2020-07-12 at 7 19 01 PM" src="https://user-images.githubusercontent.com/61646678/87264319-8bdd2d80-c474-11ea-9c88-59045f64451a.png">

 I haven't noticed there to be any item providers for them; or maybe I missed them??😅

Thanks a bunch and keep up the good work guys :)

**Comment by bryankeller** [comment]
Hi again @mosaic-engineering ! Glad you like the library 🙂

We support pinned days of the week for the vertical layout like this: 
```swift
let layoutOptions = VerticalMonthsLayoutOptions(
  pinDaysOfWeekToTop: true, // this is the important line
  alwaysShowCompleteBoundaryMonths: false)
CalendarViewContent(
      calendar: calendar,
      visibleDateRange: startDate...endDate,
      monthsLayout: .vertical(options: layoutOptions))
```

We don't support this for horizontal layouts yet, but I will likely add support for this in the future!
