### ISSUE TITLE
How to dismiss Tooltip

### ISSUE THREAD

**Issue by PIRUX-LLC** [airbnb/HorizonCalendar#263]
I have build a little app that allows choosing a date on the calendar. I show a tooltip based on the day. However, I can only select one date. No further selections are possible. Is there a way to turn this off? I'd like to be able to select any date and show a tooltip, and then select another date and show the respective tooltip for that date.

**Comment by bryankeller** [comment]
@PIRUX-LLC If you change your tooltip view to have `isUserInteractionEnabled = false`, it will fix your issue! If you need more customization, you can override `pointInside` / `hitTest`.

**Comment by bryankeller** [comment]
Some clarification here https://github.com/airbnb/HorizonCalendar/pull/264
