### ISSUE TITLE
Is HorizonCalendar a good option for presenting dates? [Question]

### ISSUE THREAD

**Issue by BredBurr** [airbnb/HorizonCalendar#277]
Hi, thank you so much for this useful library, I've been playing with it for the past two days and I like it so far!

As I see HorizonCalendar is very suitable to be used in forms for date input, is it that good for presenting dates?
I need to display past events on a calendar like:
<img width="376" alt="Screenshot" src="https://github.com/airbnb/HorizonCalendar/assets/124914915/ffa5d962-6ded-4d07-80c6-e2ef23ec855d">

If I have a data source like Event:
```swift
//Simplified:
struct Event {
    let id: UUID
    let name: String
    let date: Date
}
``` 
And I will have thousands of days that have events. 
One way to detect that a particular Day has an Event is in the `.days { day in` code block. But in my opinion, this is inefficient as I have to loop through each Event to see if the dates match to mark that Day in the calendar. So something like:
```Swift
//HorizonCalendar's SwiftUI modifier
.days { day in
    getDayView(day: day)
}

//Later in View code:
private func getDayView(day: Day) -> some View {
    //Look through all Events
    for event in events {
        //Convert Day into Date
        if let date = calendar.date(from: day.components),
           //Check if that date has an Event
            calendar.isDate(event.date, inSameDayAs: date) {
            
            return SwiftUIDayView(dayNumber: day.day, event: event)
        }
    }
    
    return SwiftUIDayView(dayNumber: day.day, event: nil)
}
```

So I have to look through all the Events in each Day which is an O(n) difficulty and a loop within a loop. 
Which brings me to my question of whether HorizonCalendar is suitable for presenting events in a calendar view?

Thanks again for your continued support!

**Comment by bryankeller** [comment]
@BredBurr you should restructure your data model (and cache it once you do so) so that you can do O(1) lookups. You would have this same issue using a `UICollectionViewDataSource` in `cellForItemAt:`, for example.
