### ISSUE TITLE
Multiple dates selection

### ISSUE THREAD

**Issue by lmr001** [airbnb/HorizonCalendar#282]
Hi
Is it possible to select multiple random dates? Not as the current day range selection is working.

**Comment by bryankeller** [comment]
Sure - that'll require custom logic in your `daySelectionHandler`. Selection logic lives in your feature code, not in the library.

One idea is to store a `Set` of selected `Date`s. You can then look in that `Set` in your `dayItemProvider` and style your day differently based on that check.
