### ISSUE TITLE
SwiftUI overlays modifier intercepts all touches in its month view

### ISSUE THREAD

**Issue by theoks** [airbnb/HorizonCalendar#291]
I am testing the `overlays(for:)` modifier, and I'm having a hard time finding a way to allow touches to pass through the `onDaySelection(_:)` modifier.

I have tried using the `.disabled(_:)` modifier, and the `.selectionDisabled(:_)` but none works. If I remove the `overlays(for:)` modifier or if I pass an empty array there, touches pass through. If the `for` parameter is not empty, no touches pass through (even with a `EmptyView` SwiftUI view in the `ViewBuilder` closure.

The README mentions setting `isUserInteractionEnabled` to false in UIKit but nothing is mentioned for SwiftUI. 

Is it a known bug, or is there a workaround I haven't found yet?

**Comment by bryankeller** [comment]
Can you try https://developer.apple.com/documentation/swiftui/view/allowshittesting(_:) and report back?

**Comment by theoks** [comment]
@bryankeller unfortunately it doesn't solve the problem.

**Comment by bryankeller** [comment]
@theoks thanks for your patience - that modifier will now work once you pull the latest changes https://github.com/airbnb/HorizonCalendar/commit/ef635338f093b548c93ad804fba63c0ee5792daa

**Comment by theoks** [comment]
@bryankeller thanks for the fix. That was a tricky one.
