### ISSUE TITLE
Public initializers for DayRangeComponents

### ISSUE THREAD

**Issue by canyoldas0** [airbnb/HorizonCalendar#300]
I was wondering why the date models such as `DayComponents`, `Day`, `Month` or some of the helper extensions on `Calendar` is set as `internal`. 

I am using this wonderful library to build my custom implementation for our app. In my case the component I build should stay at the lower module(like a design module), and when I want to use the component, I should be able to use it without importing `HorizonCalendar`. 
To do that, I need to create and use my own data models which can be used throughout the app while the component itself uses the HorizonCalendar's models.

@bryankeller thank you for the work and effort you put in this library, and would love to hear your opinion about this!

**Comment by canyoldas0** [comment]
I figured out why I don't necessarily need to use `DayRangeComponents` as a model. 👍

**Comment by bryankeller** [comment]
@canyoldas0 as it sounds like you may have already noticed, I part of HorizonCalendar's public API takes a `DateComponents`, `MonthComponents`, or related type as input. You sometimes receive these types a a convenience, but you should convert it to a `Date` object using a `Calendar` instance.

Cheers!
