### ISSUE TITLE
Question: When do you plan to create a new release tag?

### ISSUE THREAD

**Issue by alschmut** [airbnb/HorizonCalendar#311]
Hi there, I would love to use the new SwiftUI abstraction of the Horizon Calendar in a production app, but the many new implementations on the master branch are not part of any release tag yet. Do you plan on creating a git release tag sometime soon or is the current development on the master branch still partially experimental?

Thanks a lot :) Best, Alex

**Comment by bryankeller** [comment]
Hey Alex, pretty much all of the SwiftUI stuff was finished last year https://github.com/airbnb/HorizonCalendar/releases/tag/v2.0.0

If you need something newer, you can point your package manager to a specific commit, rather than a version number. Hope this helps!
