### ISSUE TITLE
Is it possible to add RTL support for Arabic and Persian calendar?

### ISSUE THREAD

**Issue by shayan77** [airbnb/HorizonCalendar#34]

**Comment by bryankeller** [comment]
This is being worked on soon @shayan77 - stay tuned!

**Comment by bryankeller** [comment]
@shayan77 thanks so much for your patience. Version 1.4.4 will have support for RTL layout thanks to this PR https://github.com/airbnb/HorizonCalendar/pull/62

I'm hoping to merge it tomorrow and will close this issue once it's merged 🙂

**Comment by bryankeller** [comment]
@shayan77 v1.5.0 is now live with RTL layout support!
