### ISSUE TITLE
Question: Center Horizontal Calendar

### ISSUE THREAD

**Issue by zachterrell57** [airbnb/HorizonCalendar#42]
Hey Guys,

Don't know if this belongs here, but I am having troubling finding a way to center the horizontal calendar, as opposed to aligning it to the left, as the default implementation suggests. In the same vein, I am also looking for the correct way to center the Month Title (August 2020) in the center of the screen, rather than aligning it to the left as well. Basically just trying to show only one month at a time with equal padding to the trailing and leading edge of the calendar, as well as center the Month Title. My apologies if these are already features and I am just missing them. I have attached two screenshots to demonstrate what I mean in regards to the alignment issue, with one being what I currently have and one being my desired outcome.

Edit: I did end up figuring out the centered header by working off the default implementation, but needed to basically copy to my source code the extended function "firstDate" since it was internally protected. Is there an easier way around this?

Thanks

![Screen Shot 2020-08-08 at 5 04 35 PM](https://user-images.githubusercontent.com/49534342/89720672-5efc3780-d99a-11ea-9f84-3356f8047ec1.png)
 

![Screen Shot 2020-08-08 at 5 04 22 PM](https://user-images.githubusercontent.com/49534342/89720654-28262180-d99a-11ea-98de-60b418670eb5.png)

**Comment by bryankeller** [comment]
Hi @zachterrell57, I was able to get the behavior you want working in the example project by adding the following to `SingleDaySelectionDemoViewController.swift`

```swift
override func viewDidLoad() {
  // ...
  calendarView.insetsLayoutMarginsFromSafeArea = false
  // ...
}
```

```swift
override func viewWillLayoutSubviews() {
    super.viewWillLayoutSubviews()

    if case .horizontal(let monthWidth) = monthsLayout {
      let marginSize = (view.bounds.width - monthWidth) / 2
      calendarView.layoutMargins.left = marginSize
      calendarView.layoutMargins.right = marginSize

      calendarView.setContent(makeContent().withInterMonthSpacing(marginSize))
    }
  }
```

Hope this helps! Note that there isn't currently any snapping behavior for the horizontal layout, but this is something I'm looking into adding in the near future!

**Comment by zachterrell57** [comment]
Thanks @bryankeller , I really appreciate it. When I implement your code on my side though I do not see the changes, but I think I could be calling this function in the wrong place. I am currently calling it in the viewDidLoad, should I be calling it somewhere else? I will add that I abstracted the constraints of the calendarView to their own function, which I am calling in the viewDidLoad, if that makes a difference.

**Comment by bryankeller** [comment]
@zachterrell57 no problem! To clarify, you're calling this code in `viewDidLoad`?

```swift
if case .horizontal(let monthWidth) = monthsLayout {
      let marginSize = (view.bounds.width - monthWidth) / 2
      calendarView.layoutMargins.left = marginSize
      calendarView.layoutMargins.right = marginSize

      calendarView.setContent(makeContent().withInterMonthSpacing(marginSize))
    }
```

You need to call it in `viewWillLayoutSubviews`, since the calculations depend on your view controller's `view` having a non-zero `bounds`. If you try to access `view.bounds` in `viewDidLoad`, it won't have a valid size yet.

Let me know if that solves it for you!

**Comment by zachterrell57** [comment]
Yes, I was calling the whole function `viewWillLayoutSubviews()` in the `viewDidLoad()`. 

`override func viewDidLoad() {
        super.viewDidLoad()
        
        if #available(iOS 13.0, *) {
          view.backgroundColor = .systemBackground
        } else {
          view.backgroundColor = .white
        }
        
        view.addSubview(calendarView)
        
        setCalendarConstraints(calendarView: calendarView)
        
        viewWillLayoutSubviews()
    }`

Should I not be doing this? If not, I guess I am confused as to where the `viewWillLayoutSubviews` is getting called.

**Comment by bryankeller** [comment]
@zachterrell57 Oh yikes, you definitely should not manually invoke view controller lifecycle functions from other lifecycle functions! `viewWillLayoutSubviews` will get called by `UIKit` at the correct time, you do not need to invoke it yourself.

**Comment by zachterrell57** [comment]
@bryankeller Gotcha, I am new to iOS development so I will make sure to read up on that. I downloaded the demo code and added your solution, but did still not get any changes so I must be doing something wrong. Should I post my implementation to the `SingleDaySelectionDemoViewController.swift` to see how it differs from your implementation?

**Comment by bryankeller** [comment]
@zachterrell57 No worries! Yeah check out some articles on `UIViewController` lifecycle events, that will make things much clearer 🙂

And yes, if you post your `SingleDaySelectionDemoViewController.swift` I'll be able to find the problem and help you find a fix!

**Comment by zachterrell57** [comment]
@bryankeller Thanks for all your help, here is the `SingleDaySelectionDemoViewController.swift`:

``` swift
import HorizonCalendar
import UIKit

// MARK: - SingleDaySelectionDemoViewController

final class SingleDaySelectionDemoViewController: UIViewController, DemoViewController {
    
    // MARK: Lifecycle
    
    init(monthsLayout: MonthsLayout) {
        self.monthsLayout = monthsLayout
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: Internal
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
 
        
        title = "Single Day Selection"
        
        calendarView.insetsLayoutMarginsFromSafeArea = false
        
        if #available(iOS 13.0, *) {
            view.backgroundColor = .systemBackground
        } else {
            view.backgroundColor = .white
        }
        
        calendarView.daySelectionHandler = { [weak self] day in
            guard let self = self else { return }
            
            self.selectedDay = day
            self.calendarView.setContent(self.makeContent())
        }
        view.addSubview(calendarView)
        
        calendarView.translatesAutoresizingMaskIntoConstraints = false
        switch monthsLayout {
        case .vertical:
            NSLayoutConstraint.activate([
                calendarView.topAnchor.constraint(equalTo: view.layoutMarginsGuide.topAnchor),
                calendarView.bottomAnchor.constraint(equalTo: view.layoutMarginsGuide.bottomAnchor),
                calendarView.leadingAnchor.constraint(
                    greaterThanOrEqualTo: view.layoutMarginsGuide.leadingAnchor),
                calendarView.trailingAnchor.constraint(
                    lessThanOrEqualTo: view.layoutMarginsGuide.trailingAnchor),
                calendarView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
                calendarView.widthAnchor.constraint(lessThanOrEqualToConstant: 375)
            ])
        case .horizontal(let monthWidth):
            NSLayoutConstraint.activate([
                calendarView.centerYAnchor.constraint(equalTo: view.layoutMarginsGuide.centerYAnchor),
                calendarView.heightAnchor.constraint(equalToConstant: monthWidth * 1.1),
                calendarView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
                calendarView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            ])
        }
    }
    
    // MARK: Private
    
    private let monthsLayout: MonthsLayout
    
    private lazy var calendarView = CalendarView(initialContent: makeContent())
    private lazy var calendar = Calendar(identifier: .gregorian)
    private lazy var dayDateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.calendar = calendar
        dateFormatter.dateFormat = DateFormatter.dateFormat(
            fromTemplate: "EEEE, MMM d, yyyy",
            options: 0,
            locale: calendar.locale ?? Locale.current)
        return dateFormatter
    }()
    
    private var selectedDay: Day?
    
    private func makeContent() -> CalendarViewContent {
        let startDate = calendar.date(from: DateComponents(year: 2020, month: 01, day: 01))!
        let endDate = calendar.date(from: DateComponents(year: 2021, month: 12, day: 31))!
        
        
        let selectedDay = self.selectedDay
        
        return CalendarViewContent(
            calendar: calendar,
            visibleDateRange: startDate...endDate,
            monthsLayout: monthsLayout)
            
            .withInterMonthSpacing(24)
            .withVerticalDayMargin(8)
            .withHorizontalDayMargin(8)
            
            .withDayItemProvider { day in
                let isSelected = day == selectedDay
                
                return CalendarItem<DayView, Day>(
                    viewModel: day,
                    styleID: isSelected ? "Selected" : "Default",
                    buildView: { DayView(isSelectedStyle: isSelected) },
                    updateViewModel: { [weak self] dayView, day in
                        dayView.dayText = "\(day.day)"
                        
                        if let date = self?.calendar.date(from: day.components) {
                            dayView.dayAccessibilityText = self?.dayDateFormatter.string(from: date)
                        } else {
                            dayView.dayAccessibilityText = nil
                        }
                    },
                    updateHighlightState: { dayView, isHighlighted in
                        dayView.isHighlighted = isHighlighted
                })
        }
    }
    
    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        
        if case .horizontal(let monthWidth) = monthsLayout {
            let marginSize = (view.bounds.width - monthWidth) / 2
            calendarView.layoutMargins.left = marginSize
            calendarView.layoutMargins.right = marginSize
            
            calendarView.setContent(makeContent().withInterMonthSpacing(marginSize))
        }
    }
    
}
```
Basically unchanged except for those changes you originally replied with. I'm sure I am missing something basic but just can't catch it. Here is the output for the above code:
![Screen Shot 2020-08-10 at 7 08 51 PM](https://user-images.githubusercontent.com/49534342/89843023-f1d4d780-db3c-11ea-9aee-80cf556d2df4.png)

**Comment by bryankeller** [comment]
@zachterrell57 your code works correctly for me. Are you on the latest version of `HorizonCalendar`? I suspect that's the problem. Version 1.2.0 includes support for setting `layoutMargins`. You might as well update to 1.3.1 though, which is the latest as of this moment!

**Comment by zachterrell57** [comment]
@bryankeller, that was it! Thanks for your help!

**Comment by bryankeller** [comment]
Awesome, glad it's working now 🙂

**Comment by epsilonmb** [comment]
@bryankeller How can I implement center horizontal calendar using 1.16 version? monthWidth is deprecated.

**Comment by konstantin-walker** [comment]
> @bryankeller How can I implement center horizontal calendar using 1.16 version? monthWidth is deprecated.

In case anyone needs to resolve the issue with the current version
```swift

final class SingleDaySelectionDemoViewController: BaseDemoViewController {
  ...
  override func viewDidLoad() {
     super.viewDidLoad()

      calendarView.insetsLayoutMarginsFromSafeArea = false
      calendarView.layoutMargins.left = 0
      calendarView.layoutMargins.right = 0
      ....
      }

  override func makeContent() -> CalendarViewContent {
    ....
    return CalendarViewContent(
      calendar: calendar,
      visibleDateRange: startDate...endDate,
      monthsLayout: .horizontal(options: .init(maximumFullyVisibleMonths: 1, scrollingBehavior: .paginatedScrolling(.init(restingPosition: .atIncrementsOfCalendarWidth, restingAffinity: .atPositionsClosestToTargetOffset)))))
      ....
      }
```
