### ISSUE TITLE
Add one initial date / initial range and scroll to good position

### ISSUE THREAD

**Issue by JulienLevallois** [airbnb/HorizonCalendar#45]
Hi, 

How can we add one initial single date / or range, 
and scroll to the good position?

Thanks

**Comment by bryankeller** [comment]
Hi @JulienLevallois, this should answer your question about how to programmatically select an individual date https://github.com/airbnb/HorizonCalendar/issues/13

If you want to add a date range selection indicator, see this section of the README https://github.com/airbnb/HorizonCalendar#adding-a-day-range-indicator

If you want to programmatically scroll to a certain month or day, you can use https://github.com/airbnb/HorizonCalendar/blob/master/Sources/Public/CalendarView.swift#L279 or https://github.com/airbnb/HorizonCalendar/blob/master/Sources/Public/CalendarView.swift#L320

----

Let me know if that answers your questions!
