### ISSUE TITLE
Multiple dates in a month are blanked out.

### ISSUE THREAD

**Issue by isaacthedeveloper** [airbnb/HorizonCalendar#46]
While leaving default code, certain dates in each month are blank. When selected they are show but otherwise they are blank... this issue does not occur to other unselected dates.

**Comment by bryankeller** [comment]
Hi @isaacthedeveloper - this happens  with the default example project code, with nothing changed? 

Can you please post the code to repro this issue? Thank you!

**Comment by isaacthedeveloper** [comment]
Hi @bryankeller Thank you for getting back so quickly! Here is the code and some screenshots.

` private func makeContent() -> CalendarViewContent {

      let startDate = gregorian.date(from: DateComponents(year: 2020, month: 01, day: 01))!
      let endDate = gregorian.date(from: DateComponents(year: 2031, month: 12, day: 31))!

      return CalendarViewContent(
        calendar: gregorian,
        visibleDateRange: startDate...endDate,
        monthsLayout: .horizontal(monthWidth: self.calendarContainerView.bounds.width - 64))
        .withInterMonthSpacing(32)
        .withDayItemProvider { day in
            let isSelected = day == self.selectedDay

            return CalendarItem<DayView, Day>(
                viewModel: day,
                styleID: isSelected ? "Selected" : "Default",
                buildView: { DayView(isSelectedStyle: isSelected) },
                updateViewModel: { [weak self] dayView, day in
                    guard let self = self else { return }

                    dayView.dayText = "\(day.day)"

                    let date = self.gregorian.date(from: day.components)
                    let today = self.gregorian.date(from: self.gregorian.dateComponents([.year, .month, .day], from: Date())) ?? Date()
                    let hasEvents = self.getCalendarDay(by: date ?? Date()) != nil
                    dayView.hasEvents = hasEvents
                    dayView.isToday = date == today

                    if let date = self.gregorian.date(from: day.components) {
                        dayView.dayAccessibilityText = self.formatter.string(from: date)
                    } else {
                        dayView.dayAccessibilityText = nil
                    }
                },
                updateHighlightState: { dayView, isHighlighted in
                    dayView.isHighlighted = isHighlighted
            })
        }
    }`

**Photo 1 shows the 14th on the month blank, then shown once selected on photo 2, photo 3 has the fifth of the month blanked out, but photo 4 shows the fifth of the month selected.**
<img width="502" alt="Screen Shot 2020-08-20 at 11 41 34 AM" src="https://user-images.githubusercontent.com/35789355/90794458-d2774080-e2da-11ea-9dbd-cbe59a8acf71.png">
<img width="512" alt="Screen Shot 2020-08-20 at 11 41 45 AM" src="https://user-images.githubusercontent.com/35789355/90794473-d60ac780-e2da-11ea-801e-3c239f47d6af.png">
<img width="517" alt="Screen Shot 2020-08-20 at 11 41 58 AM" src="https://user-images.githubusercontent.com/35789355/90794486-da36e500-e2da-11ea-986f-71edcc6c8070.png">
<img width="511" alt="Screen Shot 2020-08-20 at 11 42 07 AM" src="https://user-images.githubusercontent.com/35789355/90794487-da36e500-e2da-11ea-82d7-dbbc67119d08.png">

**Comment by bryankeller** [comment]
Thanks for the sample code, @isaacthedeveloper !

The problem here is that your `updateViewModel` implementation is making changes to the view without using the `viewModel` property. 

```swift
let hasEvents = self.getCalendarDay(by: date ?? Date()) != nil
dayView.hasEvents = hasEvents
dayView.isToday = date == today
```

`HorizonCalendar` has no way of tracking these changes, since from its perspective, your `viewModel` has not changed and therefore your view does not need to be updated.

-----

To fix this, you should create a new type to represent all of the state for your `DayView`. Something like this:

```swift
struct DayViewModel: Equatable {
  let day: Day
  let hasEvents: Bool
  let isToday: Bool
}
```

Then, change your `CalendarItem` type to `CalendarItem<DayView, DayViewModel>`.

Make sure you don't do any extra view configuration in updateViewModel, otherwise HorizonCalendar will not know about the changes. I'm currently working on some API changes that will make this much less error-prone 🙂

**Comment by bryankeller** [comment]
Also note that https://github.com/airbnb/HorizonCalendar/issues/29 is the same issue, and has more details / discussion. Cheers!

**Comment by bryankeller** [comment]
@isaacthedeveloper version 1.4.0 makes it much harder to introduce bugs like this. Check out the updated README.md and example project to see how to use the new API 🙂

**Comment by isaacthedeveloper** [comment]
@bryankeller thank you so much for the help, really appreciate it :)
