### ISSUE TITLE
Unwanted extra trailing spacing/insets

### ISSUE THREAD

**Issue by UrosZivaljevic** [airbnb/HorizonCalendar#52]
I'm having weird issue where calendar is insetted by 10ish pixels on right side by default. As you can see in picture below, highlighted view is calendarView's scrollView, and on right side after each row of items there is small spacing.

<img src="https://user-images.githubusercontent.com/26653922/92237396-94bc0f80-eeb7-11ea-84e9-731bcacad686.png" height=400 />

Only spacing related thing i'm changing is `.withInterMonthSpacing(16)`. I have custom view for DayView but same issue happens if I just use default `withDayItemModelProvider`.

Also, CalendarView is added as subview and it has 4 constraints to superview (leading, trailing, top and bottom).  
White spacing seen on sides is from superview's leading/trailing constraints so it shouldn't affect calendar. I've also tried removing that space but same issue appears.

**Comment by UrosZivaljevic** [comment]
Managed to fix the issue by setting:
```
calendarView.layoutMargins = .zero
```
By default it was (8.0, 8.0, 8.0, 8.0), but it seems during layout it didn't calculate it so there's 8px on right and 8px on left to make calendar views appear centered, instead it had 16px on right side only. 

Not sure if this is an actual issue and if it's supposed to calculate so insets are not accumulated on right side only. Feel free to close it if the issue is not related to the component itself.

Btw, thanks for this great component :+1:

**Comment by bryankeller** [comment]
Very interesting! This does seem like a bug with layout margins. I'll dig into it. Thanks for reporting!

**Comment by bryankeller** [comment]
@UrosZivaljevic are you on the latest version of `HorizonCalendar`? I'm wondering if this bug is already fixed but you might just be on an older version. I just tried on the latest version of the example project, setting the `layoutMargins.left/right = 80`, and the result looks correct to me:

![Simulator Screen Shot - iPhone 8 - 2020-09-18 at 19 19 18](https://user-images.githubusercontent.com/746571/93657040-db475900-f9e3-11ea-9b6d-b755370e683a.png)

**Comment by bryankeller** [comment]
Ah, I reproduced the bug! And I see the problem, fix coming soon! https://github.com/airbnb/HorizonCalendar/pull/63

**Comment by bryankeller** [comment]
@UrosZivaljevic this is now fixed in `v1.4.3`. Thanks again for your help!
