### ISSUE TITLE
UINavigationBar and UITabBar grey out

### ISSUE THREAD

**Issue by JackMoseley2001** [airbnb/HorizonCalendar#55]
Hello,

When using a CalendarView, I'm experiencing an issue where the UINavigationBar and UITabBar appear grey once the view is added.

I've attached a photo below to show the issue.

https://imgur.com/a/xElyIBl

Any help would be greatly appreciated.

**Comment by JackMoseley2001** [comment]
Update: seems to be due to the translucency of the navigation bar and tab bar. It can be solved by setting both to false:

```
navigationController?.navigationBar.isTranslucent = false
tabBarController?.tabBar.isTranslucent = false
```

**Comment by bryankeller** [comment]
Cool, glad you fixed it 🙂
