### ISSUE TITLE
Interactable MonthHeaderItem

### ISSUE THREAD

**Issue by tareksabry1337** [airbnb/HorizonCalendar#58]
Hi,

First of all thanks for the great work on this library it's beyond awesome.
Currently I'm trying to add two buttons to my header view but looks like whatever is added to the header isn't intractable, as such I'm unable to capture button taps.

Is this a limitation from the library or is there something to make it intractable ?

Thanks a bunch !

**Comment by tareksabry1337** [comment]
To further explain, I created this screen

![Simulator Screen Shot - iPhone SE (1st generation) - 2020-09-16 at 14 00 28](https://user-images.githubusercontent.com/45688300/93334321-0afc3280-f825-11ea-9dc6-7f8ee6a879a5.png)

But the button taps aren't being received by the view.

**Comment by bryankeller** [comment]
Hi @tareksabry1337 - thanks for bringing this to my attention! Looks like I had some code to disable user interaction on all views besides days, but that isn't actually necessary. I have a PR up here to fix it https://github.com/airbnb/HorizonCalendar/pull/59

Once it's merged, update the library to `1.4.2` in your project. Good luck!

**Comment by bryankeller** [comment]
@tareksabry1337 this bug is no fixed and merged, and `v1.4.2` with the fix is live. Thanks again!
