### ISSUE TITLE
Weekdays header and range bounds color

### ISSUE THREAD

**Issue by bekzodrakhmatof** [airbnb/HorizonCalendar#66]
Hi Team,
Thanks for the great work.
I am trying to implement this calendar into my app but I am unable to change background color of weeks. Is it possible to change?
When I have multiple range selected can I keep beginning bound and ending bound color different?

Here is the screenshot.
Thank you!

![IMG_0921](https://user-images.githubusercontent.com/23249828/97968681-546b0600-1e02-11eb-8100-01ffb8739eed.jpg)

**Comment by bryankeller** [comment]
@bekzodrakhmatof thanks for the questions. Once I merge this change https://github.com/airbnb/HorizonCalendar/pull/68, update your library (to version 1.6.0) and your weekday headers will look correct.

> When I have multiple range selected can I keep beginning bound and ending bound color different?

Sure, you can make it look any way you want. Follow the tutorial for a custom day range indicator view here https://github.com/airbnb/HorizonCalendar#adding-a-day-range-indicator

**Comment by bekzodrakhmatof** [comment]
Thank you

**Comment by bryankeller** [comment]
The fix the for the header color is merged. Please update to version 1.6.0 of the library!

**Comment by bryankeller** [comment]
@bekzodrakhmatof to have the end caps be a different color for the day ranges, you could also just give your day items a solid background color with a corner radius `width / 2`. That's how we do it in the Airbnb app! 🙂
