### ISSUE TITLE
DayView Custom Height

### ISSUE THREAD

**Issue by pierre-wehbe** [airbnb/HorizonCalendar#67]
Would it be possible to have vertical calendar have custom height for day cells?

Currently, FrameProvider has equal width and height:

let numberOfDaysPerWeek = CGFloat(7)
let availableWidth = insetWidth - (content.horizontalDayMargin * (numberOfDaysPerWeek - 1))
let points = availableWidth / numberOfDaysPerWeek
daySize = CGSize(width: points, height: points)

**Comment by bryankeller** [comment]
Hi @pierre-wehbe - the day views will always have a 1:1 aspect ratio, but you can increase the white-space in the horizontal or vertical direction using the `withHorizontalDayMargin(_ horizontalDayMargin: CGFloat)` and `withVerticalDayMargin(_ verticalDayMargin: CGFloat)` functions on `CalendarViewContent`.

In the example project, you can test this out easily.

-----

```swift
CalendarViewContent(...)
  .withVerticalDayMargin(8)
  .withHorizontalDayMargin(24)
```

![Simulator Screen Shot - iPhone 8 - 2020-11-06 at 08 28 20](https://user-images.githubusercontent.com/746571/98401671-27893f80-200a-11eb-8e11-9ee8f8fa76dc.png)

-----

```swift
CalendarViewContent(...)
  .withVerticalDayMargin(24)
  .withHorizontalDayMargin(8)
```

![Simulator Screen Shot - iPhone 8 - 2020-11-06 at 08 28 05](https://user-images.githubusercontent.com/746571/98401708-37088880-200a-11eb-908d-f5dc7d78753f.png)

**Comment by bryankeller** [comment]
I'm hoping this resolved your issue @pierre-wehbe ! Good luck.
