### ISSUE TITLE
Make sure it also works with tilted screens

### ISSUE THREAD

**Issue by ruurd** [airbnb/HorizonCalendar#7]
If one turns on the other screen orientations for the device and run the example, this calendar is not rendering properly anymore. Make sure that those device orientations are supported.

**Comment by bryankeller** [comment]
@ruurd what device / simulator / demo are you using? I'm able to repro if I rotate during on the "scroll to day with animation" demo, but only while the animation is running. Are you able to repro for any other demos?

**Comment by ruurd** [comment]
I'll make an STR for you later.

**Comment by ruurd** [comment]
STR:
- open HorizondatCalendarExample workspace
- select HorizondatCalendarExample project then target
- check all device orientations possible (all four)
- build and run
- select any example available and wait until rendering is complete
- rotate the device

EXP: calendar is rendering properly when device is being turned 90 degree CW and CCW
ACT: calendar is only partly visible

Device: iPhone11 in simulator

**Comment by bryankeller** [comment]
Ah I understand the bug! This is just a sample project layout issue. I can update the constraints so that the example project looks decent in all orientations.

**Comment by ruurd** [comment]
Maybe that's a good thing because this gives the wrong impression and might put people off...

**Comment by bryankeller** [comment]
@ruurd I just put up a PR to fix this. Thanks again for the detailed bug report

**Comment by ruurd** [comment]
Good. I'll keep an eye on that. And the bug report: noblesse oblige, right?

**Comment by bryankeller** [comment]
This is fixed now @ruurd !
