### ISSUE TITLE
Support to iOS 10

### ISSUE THREAD

**Issue by ppamorim** [airbnb/HorizonCalendar#70]
Hi, would be possible to lower the iOS requirement to 10? I tried to do some changes in a fork but they are a bit massive because of the use of the iOS 11's `layoutMargins`.

**Comment by bryankeller** [comment]
Hi @ppamorim - yikes, iOS 10!? 😅 Airbnb doesn't even support iOS 12 anymore!

I think your best bet is forking it to be honest. I don't want to add the extra complexity to the implementation, especially as I start to work toward supporting SwiftUI in the future.
