### ISSUE TITLE
[feat] Pagination for Horizontal Calendars

### ISSUE THREAD

**Issue by saudeon** [airbnb/HorizonCalendar#71]
Hey Contributors, just wanted to say thanks!

I have actually already switched over to using HorizonCalendar in one of our applications that required a vertical calendar implementation and I must say, it is one of the easiest declarative calendar options available,. so much so that we're starting to move over another application over to it.

However, we require a horizontal calendar, with pagination.
I went and attempted to set `isPagingEnabled` to the underlying `UIScrollView`, but that definitely lead to some bizarre behavior (specifically around the width I believe), and the pagination isn't true.

Is there any hint at adding an official way to set pagination for horizontal month layouts?

**Comment by saudeon** [comment]
An update on this. Did a little more digging, it looks like `scrollView.frame.size.width` is always returning `320`, thus causing issues on larger screened devices... 

Investigating more into a fix.

**Comment by bryankeller** [comment]
Hi @saudeon - I'm actively working on this now actually, so your timing is perfect 🙂 Stay tuned... there will be an official API for this without needing to play with the underlying `UIScrollView` (which won't work).

**Comment by saudeon** [comment]
@bryankeller thanks for the response, I was spending some time working on manipulating the `UIScrollView` but it sounds I went down the wrong rabbit hole. My assumption is that the work will actually be surrounding the `ScrollMetricsMutator` and/or the functionality defined in `ScrollToItemContext`?

Look forward to seeing the changes you make for this to work as expected, I am thoroughly interested in this!

**Comment by MussaCharles** [comment]
@bryankeller Any updates on this feature? Was it successfully done? Any leads will be helpful to save some time before I dive into the library internal source code 😂

**Comment by triage** [comment]
hey there @MussaCharles I know this probably doesn't help much regarding getting this feature implemented natively supported, but I had to eventually unblock myself and solve by just using SwiftUIPager to wrap multiple instances of HorizonCalendar, one per month. Performs fine!

**Comment by MussaCharles** [comment]
Hi @triage  Thanks for sharing the work around. However the app I am working on is based on UIKit for backward compatibility from iOS 11+ . But I will try to play around with SwiftUIPager some days in the future :)

**Comment by saudeon** [comment]
@MussaCharles you could most likely achieve the same workaround utilizing UIPageController I believe in UIKit...

I'm not 100% sure when that was made available API wise though.

**Comment by MussaCharles** [comment]
Hi @saudeon I was thinking about UIPageController but a little hesitant to try out as it seems like it will  needs a lot of manual work to make it work with HorizonCalendar, I would like to try it in the future when I have enough time. 

Btw how about your approach playing with the underlying UIScrollView paging behavior go? Did you continue working on it or stopped after @bryankeller said it won't work? 😢

**Comment by saudeon** [comment]
@MussaCharles definitely would require a lot of work to get it going with the workaround...

I haven't played anymore with the underlying UIScrollView solution as I got pretty fair and then realized it wasn't the right route to go down...

I know that there is a branch for 1.7.0 that has some more horizontal work, but my assumption is that @bryankeller will have something sorted in the near future... if you can push back release?

**Comment by MussaCharles** [comment]
@saudeon  I guess we might have to wait for native support from 1.7.0 release. 
Since I have time constraints, am gonna try a couple of other available options or build a simple custom solution using Calendar API. But before  that I will try to check these two other options. 
1. [JTAppleCalendar](https://github.com/patchthecode/JTAppleCalendar)
2. [FSCalendar](https://github.com/WenchaoD/FSCalendar)

If any of you (@saudeon & @triage) have bad experience with the mentioned alternatives 1 & 2 above please let me know. 

ps: I will keep an eye on next release to see if AirBnb HorizonCalendar will have this feature implemented.

**Comment by saudeon** [comment]
@MussaCharles with the time constraints, the two projects you mentioned should enable you to move past this.

I have utilized both, neither are as nice as HorizonCalendar but they're more feature complete (due to age of library if anything).

Hopefully we can get 1.7.0 with pagination soon! 🤘🏻

**Comment by MussaCharles** [comment]
Thanks for detailed explanation @saudeon  I went went with alternative 1 above and yes indeed I managed to move super fast :) 

Same here,I will definitely get back and try this Libray again soon after shipping the current expected release to AppStore.

Happy Coding 💪💪

**Comment by bryankeller** [comment]
Thanks all for your patience while I made foundational changes to get this implemented the right way. Expect 1.7.0 to go live, with horizontal-pagination support, by end of week. The major PR is here https://github.com/airbnb/HorizonCalendar/pull/93

@MussaCharles maybe it's not too late to switch back to `HorizonCalendar` 😄

**Comment by MussaCharles** [comment]
Wow! great work @bryankeller , thanks for finally landing this feature. I will definitely get back to and explore it soon!

**Comment by bryankeller** [comment]
v1.7.0 is now available with horizontal pagination support 🙂
