### ISSUE TITLE
Intial Date selection is not reseting

### ISSUE THREAD

**Issue by Safa-786** [airbnb/HorizonCalendar#74]
how to unselect initial date once another date is selected

**Comment by saudeon** [comment]
Within the `daySelectionHandler` it is recommended that you save the selected date and then reload your content.

My `daySelectionHandler` looks like the following.

```
calendarView.daySelectionHandler = { [weak self] day in
            guard let self = self else { return }

            self.selectedDay = day

            let newContent = self.makeContent()
            self.calendarView?.setContent(newContent)
            
        }
```

When re-setting the calendarView content, it builds up the appropriate views and you can set your selection style appropriately in there. This is contained within the `makeContent` function.

**Comment by Safa-786** [comment]
if i try to convert string (2020-11-27 00:00:00.000) to Date i am getting previous date (2020-11-26 18:30:00 +0000)

**Comment by saudeon** [comment]
There are lots of information surrounding Dates and how they are handled within Swift. These questions are a lot more broader than this project. Here's a few helpful links.

[Working with Dates - Hacking with Swift](https://www.hackingwithswift.com/books/ios-swiftui/working-with-dates
[Formatter - NSHipster](https://nshipster.com/formatter/)
[DateComponents - NSHipster](https://nshipster.com/datecomponents/)

There's also an abundance of information on SO as well.

**Comment by bryankeller** [comment]
Thanks for covering this @saudeon.

@Safa-786 try something like this:

```swift
calendarView.daySelectionHandler = { [weak self] day in
    guard let self = self else { return }

    if self.selectedDay != nil {
        self.selectedDay = nil
    } else {
        self.selectedDay = day
    }

    let newContent = self.makeContent()
    self.calendarView?.setContent(newContent)
}
```

The key thing is to always re-render your content whenever something in your model changes. It's similar to how SwiftUI works 🙂
