### ISSUE TITLE
Question: Increase margin between pinned day of week separator and month label

### ISSUE THREAD

**Issue by derrickleemy** [airbnb/HorizonCalendar#84]
![Screenshot 2020-12-27 at 4 03 42 PM](https://user-images.githubusercontent.com/28346075/103166450-1962dd00-485d-11eb-871a-739343af14d8.png)

Hi all, how do i increase the margin between the pinned day of week separator and the month label?

**Comment by bryankeller** [comment]
Hi @derrickleemy, I think the easiest way would be to increase the height of your month header (and keep the label bottom-aligned). Does that work for your designs?

```swift
func setUpMonthLabelConstraints() {
  monthLabel.topAnchor.constraint(equalTo: layoutMarginsGuide.topAnchor, constant: 24).isActive = true
  // leading, trailing, and bottom constraints
}
```

**Comment by derrickleemy** [comment]
> Hi @derrickleemy, I think the easiest way would be to increase the height of your month header (and keep the label bottom-aligned). Does that work for your designs?
> 
> ```swift
> func setUpMonthLabelConstraints() {
>   monthLabel.topAnchor.constraint(equalTo: layoutMarginsGuide.topAnchor, constant: 24).isActive = true
>   // leading, trailing, and bottom constraints
> }
> ```

Thank you for your response! But i'm not sure how to implement that easy method of yours. 
Do i do it within `.withDaysOfTheWeekRowSeparator` or `.withMonthHeaderItemModelProvider`?

**Comment by bryankeller** [comment]
You'll want to do it in the `UIView` subclass that you're using for the month header. If you're just using a `UILabel` directly, you won't be able to add additional top padding unless you wrap it in a container `UIView`, which is where you'll set up the top constraint with 24pt of additional padding.
