### ISSUE TITLE
Question: Get the height of the displayed content

### ISSUE THREAD

**Issue by cuongtvwru** [airbnb/HorizonCalendar#88]
Hi all, 
How can I get the height of the displayed content?. In my case I display the current month, thanks

**Comment by bryankeller** [comment]
Hi @cuongtvwru - there's not currently an API to do this. Can you explain your use-case a bit more?

**Comment by bryankeller** [comment]
Starting in version 1.11.0 (just released), `CalendarView` now has an `intrinsicContentSize.height` equal to the exact amount of space needed to fit all of the rows of a month, given the current width / other layout metrics. That means that you can add a horizontally-scrolling `CalendarView` to your view hierarchy, constrain its width, and the height will be set based on the `intrinsicContentSize`.

If you want to get the height if the displayed content, simply check `calendarView.bounds.height` after your view hierarchy has been completely laid out.
