### ISSUE TITLE
Day of Week background 

### ISSUE THREAD

**Issue by SaitamLe** [airbnb/HorizonCalendar#89]
Is there a way to change the background color of the days of week section when those are pinned to the top of the calendar?
 
<img width="409" alt="Bildschirmfoto 2021-01-11 um 10 07 47" src="https://user-images.githubusercontent.com/23743401/104162559-1fc48d80-53f5-11eb-9525-afa7d155baf7.png">

**Comment by bryankeller** [comment]
Hi @SaitamLe - sorry for the delay on this. I think this seems like something that we can support. I'll need to add a new API to configure this on CalendarViewContent, but it should be pretty straightforward. I'll get a change up this week for it.

**Comment by iosdevmax** [comment]
Looking forward to this change as well :)

**Comment by haffez23** [comment]
> und color of the days of week section when those are pinned to the top of the calendar

How did u display three characters in days of week ?

**Comment by Mordil** [comment]
@haffez23 

Unfortunately your only option right now is to just fully override the view with your own implementation with `withDayOfWeekItemModelProvider` which provides `Month?, Int` parameters with the 2nd being the `dayOfWeekIndex` that you can index into `Calendar` to get which day it is and format the value how you want

**Comment by bryankeller** [comment]
Thinking this through a bit more, it seems like right now there are 2 options:

- Use the default items, which don't allow any customization
- Provide your own custom items, which allow full customization

I think there's a middle-ground here, where a customization point is provided for the default items. I agree it seems silly to need to create your own custom items just to change a font size or a background color. Will give this some thought in the next few days.

**Comment by Mordil** [comment]
@bryankeller When I was going to implement my header, what I really wanted was to just access and provide an instance of the default's `InvariantViewProperties` but the entire struct's hierarchy is internal

**Comment by bryankeller** [comment]
@Mordil makes total sense! My current plan is to just expose these publicly. For the default `DayView`, I'm just going to open source the one I built for Airbnb internally, which has iPad pointer interaction support, configurable haptics, and more 🙂

**Comment by bryankeller** [comment]
Hey all, I've got a PR out which exposes configurable default views for month headers, days of the week, and individual days https://github.com/airbnb/HorizonCalendar/pull/140

Should be merged in the next few days - hopefully you can delete some code on your end once this lands! 🤞

**Comment by bryankeller** [comment]
Merged! `v1.10.0` contains a public `DayView`, `DayOfWeekView` and `MonthHeaderView`.
